# Copyright Confidential Containers Contributors
#
# SPDX-License-Identifier: Apache-2.0
#
# Install the containerd runtime. The operator will replace the container
# runtime, so this is required only to bootstrap the cluster.
#
---
- hosts: all:localhost
  become: yes
  tasks:
    - name: Install containerd.io from distro
      package:
        name: "containerd"
        state: present
    # The docker package overwrite the /etc/containerd/config.toml installed
    # by the containerd.io package. As a result we are hit by the following
    # problems:
    #
    #   - `kubeadm init` fails on preflight checks if containerd has 'cri'
    #   plug-in disabled. See https://github.com/containerd/containerd/issues/4581
    #   - Kubelet fails to scan the containerd endpoint after ccruntime is
    #   deployed then the node gets marked 'UnReady'. See
    #   https://github.com/containerd/containerd/issues/4581
    #
    # Those issues are solved by re-generating the containerd configuration
    # file with its defaults.
    - name: mkdir /etc/containerd
      file:
        path: /etc/containerd
        state: directory
    - name: Re-create containerd config
      shell: containerd config default > /etc/containerd/config.toml
      args:
        executable: /bin/bash
    - name: Restart containerd service
      service:
        name: containerd
        enabled: yes
        state: restarted
    #
    # Undo the installation.
    #
    - name: Revert containerd config to defaults
      tags: undo
      block:
        - name: Check containerd is installed
          shell: systemctl list-unit-files | grep containerd
          register: containerd_exist
          ignore_errors: yes
        - name: Re-create containerd config
          shell: containerd config default > /etc/containerd/config.toml
          when: containerd_exist.rc == 0
        - name: Restart containerd service
          service:
            name: containerd
            enabled: yes
            state: restarted
          when: containerd_exist.rc == 0
