# Copyright Confidential Containers Contributors
#
# SPDX-License-Identifier: Apache-2.0
#
# Install kubeadm and everything else needed to bring up a single node
# k8s cluster.
#
---
- hosts: all:localhost
  become: yes
  vars:
    cni_home: "/opt/cni"
    cni_version: "v1.1.1"
    flannel_home: "/opt/flannel"
    flannel_version: "v0.19.1"
    kubeadm_cri_runtime_socket: "/run/containerd/containerd.sock"
    kubeadm_conf_dir: "/etc/kubeadm"
    kubelet_bin: "/usr/local/bin/kubelet"
    kubelet_service_dir: "/etc/systemd/system/kubelet.service.d"
    kubelet_service_file: "/etc/systemd/system/kubelet.service"
    # Use 'cgroupfs' with containerd, 'systemd' with crio?
    kubelet_cgroup_driver: "cgroupfs"
  tasks:
    #
    # Undo the kubeadm installation. Assume that ../cluster/down.sh is executed
    # before.
    #
    - name: Uninstall kubeadm
      tags: undo
      block:
        - name: Uninstall flannel
          file:
            path: "{{ flannel_home }}"
            state: absent
        - name: Check kubelet is installed
          shell: systemctl list-unit-files | grep kubelet
          register: kubelet_exist
          ignore_errors: yes
        - name: Stop kubelet service
          service:
            name: kubelet
            state: stopped
          when: kubelet_exist.rc == 0
        - name: Delete kubelet service files
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "{{ kubelet_service_file }}"
            - "{{ kubelet_service_dir }}"
        - name: Delete the kubeadm configuration directory
          file:
            path: "{{ kubeadm_conf_dir }}"
            state: absent
        - name: Remove kube binaries
          file:
            path: "/usr/local/bin/{{ item }}"
            state: absent
          with_items:
            - crictl
            - kubeadm
            - kubectl
            - kubelet
        - name: Uninstall cni
          file:
            path: "{{ cni_home }}"
            state: absent
        # TODO: what to do with swap?