# permissions for end users to edit confidentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: confidential-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: akash-confidential-containers-operator
    app.kubernetes.io/part-of: akash-confidential-containers-operator
    app.kubernetes.io/managed-by: kustomize
  name: confidential-editor-role
rules:
- apiGroups:
  - preview.cypherpunk.io
  resources:
  - confidentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - preview.cypherpunk.io
  resources:
  - confidentials/status
  verbs:
  - get
