---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - preview.cypherpunk.io
  resources:
  - confidentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - preview.cypherpunk.io
  resources:
  - confidentials/finalizers
  verbs:
  - update
- apiGroups:
  - preview.cypherpunk.io
  resources:
  - confidentials/status
  verbs:
  - get
  - patch
  - update
