apiVersion: v1
kind: Pod
metadata:
  name: kata-web
  labels:
    role: myrole
spec:
  runtimeClassName: kata-qemu-sev
  containers:
    - name: kata-web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP